// Generated by gencpp from file geobot_navigation_rupes/Path.msg
// DO NOT EDIT!


#ifndef GEOBOT_NAVIGATION_RUPES_MESSAGE_PATH_H
#define GEOBOT_NAVIGATION_RUPES_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <geobot_navigation_rupes/PathRequest.h>
#include <geobot_navigation_rupes/PathResponse.h>


namespace geobot_navigation_rupes
{

struct Path
{

typedef PathRequest Request;
typedef PathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Path
} // namespace geobot_navigation_rupes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geobot_navigation_rupes::Path > {
  static const char* value()
  {
    return "f305bdd89c3cf25126ae31f8077dfa1b";
  }

  static const char* value(const ::geobot_navigation_rupes::Path&) { return value(); }
};

template<>
struct DataType< ::geobot_navigation_rupes::Path > {
  static const char* value()
  {
    return "geobot_navigation_rupes/Path";
  }

  static const char* value(const ::geobot_navigation_rupes::Path&) { return value(); }
};


// service_traits::MD5Sum< ::geobot_navigation_rupes::PathRequest> should match 
// service_traits::MD5Sum< ::geobot_navigation_rupes::Path > 
template<>
struct MD5Sum< ::geobot_navigation_rupes::PathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geobot_navigation_rupes::Path >::value();
  }
  static const char* value(const ::geobot_navigation_rupes::PathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geobot_navigation_rupes::PathRequest> should match 
// service_traits::DataType< ::geobot_navigation_rupes::Path > 
template<>
struct DataType< ::geobot_navigation_rupes::PathRequest>
{
  static const char* value()
  {
    return DataType< ::geobot_navigation_rupes::Path >::value();
  }
  static const char* value(const ::geobot_navigation_rupes::PathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geobot_navigation_rupes::PathResponse> should match 
// service_traits::MD5Sum< ::geobot_navigation_rupes::Path > 
template<>
struct MD5Sum< ::geobot_navigation_rupes::PathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geobot_navigation_rupes::Path >::value();
  }
  static const char* value(const ::geobot_navigation_rupes::PathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geobot_navigation_rupes::PathResponse> should match 
// service_traits::DataType< ::geobot_navigation_rupes::Path > 
template<>
struct DataType< ::geobot_navigation_rupes::PathResponse>
{
  static const char* value()
  {
    return DataType< ::geobot_navigation_rupes::Path >::value();
  }
  static const char* value(const ::geobot_navigation_rupes::PathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEOBOT_NAVIGATION_RUPES_MESSAGE_PATH_H
