// Generated by gencpp from file geobot_navigation_rupes/PathRequest.msg
// DO NOT EDIT!


#ifndef GEOBOT_NAVIGATION_RUPES_MESSAGE_PATHREQUEST_H
#define GEOBOT_NAVIGATION_RUPES_MESSAGE_PATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace geobot_navigation_rupes
{
template <class ContainerAllocator>
struct PathRequest_
{
  typedef PathRequest_<ContainerAllocator> Type;

  PathRequest_()
    : a(0.0)
    , b(0.0)  {
    }
  PathRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;




  typedef boost::shared_ptr< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathRequest_

typedef ::geobot_navigation_rupes::PathRequest_<std::allocator<void> > PathRequest;

typedef boost::shared_ptr< ::geobot_navigation_rupes::PathRequest > PathRequestPtr;
typedef boost::shared_ptr< ::geobot_navigation_rupes::PathRequest const> PathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace geobot_navigation_rupes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geobot_navigation_rupes': ['/home/administrator/sensors_ws/src/geobot_navigation_rupes/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f6326d24b4937f854196fd3a843f42e";
  }

  static const char* value(const ::geobot_navigation_rupes::PathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f6326d24b4937f8ULL;
  static const uint64_t static_value2 = 0x54196fd3a843f42eULL;
};

template<class ContainerAllocator>
struct DataType< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geobot_navigation_rupes/PathRequest";
  }

  static const char* value(const ::geobot_navigation_rupes::PathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n\
float32 b\n\
";
  }

  static const char* value(const ::geobot_navigation_rupes::PathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geobot_navigation_rupes::PathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geobot_navigation_rupes::PathRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEOBOT_NAVIGATION_RUPES_MESSAGE_PATHREQUEST_H
