// Generated by gencpp from file geobot_navigation/GapDirection.msg
// DO NOT EDIT!


#ifndef GEOBOT_NAVIGATION_MESSAGE_GAPDIRECTION_H
#define GEOBOT_NAVIGATION_MESSAGE_GAPDIRECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace geobot_navigation
{
template <class ContainerAllocator>
struct GapDirection_
{
  typedef GapDirection_<ContainerAllocator> Type;

  GapDirection_()
    : header()
    , gap_seq(0)
    , sr_heading(0.0)
    , sr_diff(0.0)
    , sl_heading(0.0)
    , sl_diff(0.0)  {
    }
  GapDirection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gap_seq(0)
    , sr_heading(0.0)
    , sr_diff(0.0)
    , sl_heading(0.0)
    , sl_diff(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _gap_seq_type;
  _gap_seq_type gap_seq;

   typedef float _sr_heading_type;
  _sr_heading_type sr_heading;

   typedef float _sr_diff_type;
  _sr_diff_type sr_diff;

   typedef float _sl_heading_type;
  _sl_heading_type sl_heading;

   typedef float _sl_diff_type;
  _sl_diff_type sl_diff;




  typedef boost::shared_ptr< ::geobot_navigation::GapDirection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geobot_navigation::GapDirection_<ContainerAllocator> const> ConstPtr;

}; // struct GapDirection_

typedef ::geobot_navigation::GapDirection_<std::allocator<void> > GapDirection;

typedef boost::shared_ptr< ::geobot_navigation::GapDirection > GapDirectionPtr;
typedef boost::shared_ptr< ::geobot_navigation::GapDirection const> GapDirectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geobot_navigation::GapDirection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geobot_navigation::GapDirection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace geobot_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geobot_navigation': ['/home/administrator/sensors_ws/src/geobot_navigation/msg', '/home/administrator/sensors_ws/devel/share/geobot_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::geobot_navigation::GapDirection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geobot_navigation::GapDirection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geobot_navigation::GapDirection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geobot_navigation::GapDirection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geobot_navigation::GapDirection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geobot_navigation::GapDirection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geobot_navigation::GapDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db868e1527d93c1574e7467a1c69f2bc";
  }

  static const char* value(const ::geobot_navigation::GapDirection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb868e1527d93c15ULL;
  static const uint64_t static_value2 = 0x74e7467a1c69f2bcULL;
};

template<class ContainerAllocator>
struct DataType< ::geobot_navigation::GapDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geobot_navigation/GapDirection";
  }

  static const char* value(const ::geobot_navigation::GapDirection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geobot_navigation::GapDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 gap_seq       \n\
float32 sr_heading        \n\
float32 sr_diff      \n\
float32 sl_heading     \n\
float32 sl_diff     \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::geobot_navigation::GapDirection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geobot_navigation::GapDirection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gap_seq);
      stream.next(m.sr_heading);
      stream.next(m.sr_diff);
      stream.next(m.sl_heading);
      stream.next(m.sl_diff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GapDirection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geobot_navigation::GapDirection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geobot_navigation::GapDirection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gap_seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gap_seq);
    s << indent << "sr_heading: ";
    Printer<float>::stream(s, indent + "  ", v.sr_heading);
    s << indent << "sr_diff: ";
    Printer<float>::stream(s, indent + "  ", v.sr_diff);
    s << indent << "sl_heading: ";
    Printer<float>::stream(s, indent + "  ", v.sl_heading);
    s << indent << "sl_diff: ";
    Printer<float>::stream(s, indent + "  ", v.sl_diff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEOBOT_NAVIGATION_MESSAGE_GAPDIRECTION_H
