// Generated by gencpp from file geobot_navigation/GetPlan.msg
// DO NOT EDIT!


#ifndef GEOBOT_NAVIGATION_MESSAGE_GETPLAN_H
#define GEOBOT_NAVIGATION_MESSAGE_GETPLAN_H

#include <ros/service_traits.h>


#include <geobot_navigation/GetPlanRequest.h>
#include <geobot_navigation/GetPlanResponse.h>


namespace geobot_navigation
{

struct GetPlan
{

typedef GetPlanRequest Request;
typedef GetPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlan
} // namespace geobot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geobot_navigation::GetPlan > {
  static const char* value()
  {
    return "4cd193516629606673980274d58ad6f9";
  }

  static const char* value(const ::geobot_navigation::GetPlan&) { return value(); }
};

template<>
struct DataType< ::geobot_navigation::GetPlan > {
  static const char* value()
  {
    return "geobot_navigation/GetPlan";
  }

  static const char* value(const ::geobot_navigation::GetPlan&) { return value(); }
};


// service_traits::MD5Sum< ::geobot_navigation::GetPlanRequest> should match 
// service_traits::MD5Sum< ::geobot_navigation::GetPlan > 
template<>
struct MD5Sum< ::geobot_navigation::GetPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geobot_navigation::GetPlan >::value();
  }
  static const char* value(const ::geobot_navigation::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geobot_navigation::GetPlanRequest> should match 
// service_traits::DataType< ::geobot_navigation::GetPlan > 
template<>
struct DataType< ::geobot_navigation::GetPlanRequest>
{
  static const char* value()
  {
    return DataType< ::geobot_navigation::GetPlan >::value();
  }
  static const char* value(const ::geobot_navigation::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geobot_navigation::GetPlanResponse> should match 
// service_traits::MD5Sum< ::geobot_navigation::GetPlan > 
template<>
struct MD5Sum< ::geobot_navigation::GetPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geobot_navigation::GetPlan >::value();
  }
  static const char* value(const ::geobot_navigation::GetPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geobot_navigation::GetPlanResponse> should match 
// service_traits::DataType< ::geobot_navigation::GetPlan > 
template<>
struct DataType< ::geobot_navigation::GetPlanResponse>
{
  static const char* value()
  {
    return DataType< ::geobot_navigation::GetPlan >::value();
  }
  static const char* value(const ::geobot_navigation::GetPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEOBOT_NAVIGATION_MESSAGE_GETPLAN_H
