// Generated by gencpp from file geobot_navigation/SetGoal.msg
// DO NOT EDIT!


#ifndef GEOBOT_NAVIGATION_MESSAGE_SETGOAL_H
#define GEOBOT_NAVIGATION_MESSAGE_SETGOAL_H

#include <ros/service_traits.h>


#include <geobot_navigation/SetGoalRequest.h>
#include <geobot_navigation/SetGoalResponse.h>


namespace geobot_navigation
{

struct SetGoal
{

typedef SetGoalRequest Request;
typedef SetGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoal
} // namespace geobot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geobot_navigation::SetGoal > {
  static const char* value()
  {
    return "85ae384b155cfbcdf597bf321f1d0169";
  }

  static const char* value(const ::geobot_navigation::SetGoal&) { return value(); }
};

template<>
struct DataType< ::geobot_navigation::SetGoal > {
  static const char* value()
  {
    return "geobot_navigation/SetGoal";
  }

  static const char* value(const ::geobot_navigation::SetGoal&) { return value(); }
};


// service_traits::MD5Sum< ::geobot_navigation::SetGoalRequest> should match 
// service_traits::MD5Sum< ::geobot_navigation::SetGoal > 
template<>
struct MD5Sum< ::geobot_navigation::SetGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geobot_navigation::SetGoal >::value();
  }
  static const char* value(const ::geobot_navigation::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geobot_navigation::SetGoalRequest> should match 
// service_traits::DataType< ::geobot_navigation::SetGoal > 
template<>
struct DataType< ::geobot_navigation::SetGoalRequest>
{
  static const char* value()
  {
    return DataType< ::geobot_navigation::SetGoal >::value();
  }
  static const char* value(const ::geobot_navigation::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geobot_navigation::SetGoalResponse> should match 
// service_traits::MD5Sum< ::geobot_navigation::SetGoal > 
template<>
struct MD5Sum< ::geobot_navigation::SetGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geobot_navigation::SetGoal >::value();
  }
  static const char* value(const ::geobot_navigation::SetGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geobot_navigation::SetGoalResponse> should match 
// service_traits::DataType< ::geobot_navigation::SetGoal > 
template<>
struct DataType< ::geobot_navigation::SetGoalResponse>
{
  static const char* value()
  {
    return DataType< ::geobot_navigation::SetGoal >::value();
  }
  static const char* value(const ::geobot_navigation::SetGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEOBOT_NAVIGATION_MESSAGE_SETGOAL_H
