// Generated by gencpp from file gap_finding_pkg/Gap.msg
// DO NOT EDIT!


#ifndef GAP_FINDING_PKG_MESSAGE_GAP_H
#define GAP_FINDING_PKG_MESSAGE_GAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gap_finding_pkg
{
template <class ContainerAllocator>
struct Gap_
{
  typedef Gap_<ContainerAllocator> Type;

  Gap_()
    : header()
    , gap_width(0.0)
    , dist_right(0.0)
    , dist_left(0.0)
    , angle_right(0.0)
    , angle_left(0.0)  {
    }
  Gap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gap_width(0.0)
    , dist_right(0.0)
    , dist_left(0.0)
    , angle_right(0.0)
    , angle_left(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _gap_width_type;
  _gap_width_type gap_width;

   typedef float _dist_right_type;
  _dist_right_type dist_right;

   typedef float _dist_left_type;
  _dist_left_type dist_left;

   typedef float _angle_right_type;
  _angle_right_type angle_right;

   typedef float _angle_left_type;
  _angle_left_type angle_left;




  typedef boost::shared_ptr< ::gap_finding_pkg::Gap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gap_finding_pkg::Gap_<ContainerAllocator> const> ConstPtr;

}; // struct Gap_

typedef ::gap_finding_pkg::Gap_<std::allocator<void> > Gap;

typedef boost::shared_ptr< ::gap_finding_pkg::Gap > GapPtr;
typedef boost::shared_ptr< ::gap_finding_pkg::Gap const> GapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gap_finding_pkg::Gap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gap_finding_pkg::Gap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gap_finding_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gap_finding_pkg': ['/home/administrator/sensors_ws/src/gap_finding_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding_pkg::Gap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding_pkg::Gap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding_pkg::Gap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding_pkg::Gap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding_pkg::Gap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding_pkg::Gap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gap_finding_pkg::Gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79c057cbab3544dbadcc4f7af24d22c1";
  }

  static const char* value(const ::gap_finding_pkg::Gap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79c057cbab3544dbULL;
  static const uint64_t static_value2 = 0xadcc4f7af24d22c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::gap_finding_pkg::Gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gap_finding_pkg/Gap";
  }

  static const char* value(const ::gap_finding_pkg::Gap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gap_finding_pkg::Gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 gap_width          # the width of the widest gap[m]\n\
float32 dist_right         # distance to the edge of obstacle on the right[m]\n\
float32 dist_left          # distance to the edge of obstacle on the left[m]\n\
float32 angle_right        # right scan angle border [rad]\n\
float32 angle_left         # left scan angle border [rad]\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gap_finding_pkg::Gap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gap_finding_pkg::Gap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gap_width);
      stream.next(m.dist_right);
      stream.next(m.dist_left);
      stream.next(m.angle_right);
      stream.next(m.angle_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gap_finding_pkg::Gap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gap_finding_pkg::Gap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gap_width: ";
    Printer<float>::stream(s, indent + "  ", v.gap_width);
    s << indent << "dist_right: ";
    Printer<float>::stream(s, indent + "  ", v.dist_right);
    s << indent << "dist_left: ";
    Printer<float>::stream(s, indent + "  ", v.dist_left);
    s << indent << "angle_right: ";
    Printer<float>::stream(s, indent + "  ", v.angle_right);
    s << indent << "angle_left: ";
    Printer<float>::stream(s, indent + "  ", v.angle_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAP_FINDING_PKG_MESSAGE_GAP_H
