// Generated by gencpp from file gap_finding_pkg/GapArray.msg
// DO NOT EDIT!


#ifndef GAP_FINDING_PKG_MESSAGE_GAPARRAY_H
#define GAP_FINDING_PKG_MESSAGE_GAPARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gap_finding_pkg/Gap.h>

namespace gap_finding_pkg
{
template <class ContainerAllocator>
struct GapArray_
{
  typedef GapArray_<ContainerAllocator> Type;

  GapArray_()
    : header()
    , gaps()  {
    }
  GapArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gaps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gap_finding_pkg::Gap_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gap_finding_pkg::Gap_<ContainerAllocator> >::other >  _gaps_type;
  _gaps_type gaps;




  typedef boost::shared_ptr< ::gap_finding_pkg::GapArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gap_finding_pkg::GapArray_<ContainerAllocator> const> ConstPtr;

}; // struct GapArray_

typedef ::gap_finding_pkg::GapArray_<std::allocator<void> > GapArray;

typedef boost::shared_ptr< ::gap_finding_pkg::GapArray > GapArrayPtr;
typedef boost::shared_ptr< ::gap_finding_pkg::GapArray const> GapArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gap_finding_pkg::GapArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gap_finding_pkg::GapArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gap_finding_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gap_finding_pkg': ['/home/administrator/sensors_ws/src/gap_finding_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding_pkg::GapArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding_pkg::GapArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding_pkg::GapArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d5ee3363f969383412dfa34da32c3c4";
  }

  static const char* value(const ::gap_finding_pkg::GapArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d5ee3363f969383ULL;
  static const uint64_t static_value2 = 0x412dfa34da32c3c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gap_finding_pkg/GapArray";
  }

  static const char* value(const ::gap_finding_pkg::GapArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
gap_finding_pkg/Gap[] gaps\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: gap_finding_pkg/Gap\n\
Header header\n\
\n\
float32 gap_width          # the width of the widest gap[m]\n\
float32 dist_right         # distance to the edge of obstacle on the right[m]\n\
float32 dist_left          # distance to the edge of obstacle on the left[m]\n\
float32 angle_right        # right scan angle border [rad]\n\
float32 angle_left         # left scan angle border [rad]\n\
";
  }

  static const char* value(const ::gap_finding_pkg::GapArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gaps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GapArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gap_finding_pkg::GapArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gap_finding_pkg::GapArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gaps[]" << std::endl;
    for (size_t i = 0; i < v.gaps.size(); ++i)
    {
      s << indent << "  gaps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gap_finding_pkg::Gap_<ContainerAllocator> >::stream(s, indent + "    ", v.gaps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAP_FINDING_PKG_MESSAGE_GAPARRAY_H
