// Generated by gencpp from file pointcloud_to_laserscan/Velocity_multiplier.msg
// DO NOT EDIT!


#ifndef POINTCLOUD_TO_LASERSCAN_MESSAGE_VELOCITY_MULTIPLIER_H
#define POINTCLOUD_TO_LASERSCAN_MESSAGE_VELOCITY_MULTIPLIER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pointcloud_to_laserscan
{
template <class ContainerAllocator>
struct Velocity_multiplier_
{
  typedef Velocity_multiplier_<ContainerAllocator> Type;

  Velocity_multiplier_()
    : header()
    , ang_right(0.0)
    , ang_left(0.0)
    , lin_forward(0.0)
    , lin_backward(0.0)  {
    }
  Velocity_multiplier_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ang_right(0.0)
    , ang_left(0.0)
    , lin_forward(0.0)
    , lin_backward(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _ang_right_type;
  _ang_right_type ang_right;

   typedef float _ang_left_type;
  _ang_left_type ang_left;

   typedef float _lin_forward_type;
  _lin_forward_type lin_forward;

   typedef float _lin_backward_type;
  _lin_backward_type lin_backward;




  typedef boost::shared_ptr< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity_multiplier_

typedef ::pointcloud_to_laserscan::Velocity_multiplier_<std::allocator<void> > Velocity_multiplier;

typedef boost::shared_ptr< ::pointcloud_to_laserscan::Velocity_multiplier > Velocity_multiplierPtr;
typedef boost::shared_ptr< ::pointcloud_to_laserscan::Velocity_multiplier const> Velocity_multiplierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pointcloud_to_laserscan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pointcloud_to_laserscan': ['/home/administrator/sensors_ws/src/pointcloud_to_laserscan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6bee81ca0235061272a09ce6e9fbf49";
  }

  static const char* value(const ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6bee81ca0235061ULL;
  static const uint64_t static_value2 = 0x272a09ce6e9fbf49ULL;
};

template<class ContainerAllocator>
struct DataType< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pointcloud_to_laserscan/Velocity_multiplier";
  }

  static const char* value(const ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 ang_right         # right angular velocity multiplier [0 to 1]\n\
float32 ang_left          # left angular velocity multiplier [0 to 1]\n\
float32 lin_forward        # forward linear velocity multiplier [0 to 1]\n\
float32 lin_backward         # backward linear velocity multiplier [0 to 1]\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ang_right);
      stream.next(m.ang_left);
      stream.next(m.lin_forward);
      stream.next(m.lin_backward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity_multiplier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pointcloud_to_laserscan::Velocity_multiplier_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ang_right: ";
    Printer<float>::stream(s, indent + "  ", v.ang_right);
    s << indent << "ang_left: ";
    Printer<float>::stream(s, indent + "  ", v.ang_left);
    s << indent << "lin_forward: ";
    Printer<float>::stream(s, indent + "  ", v.lin_forward);
    s << indent << "lin_backward: ";
    Printer<float>::stream(s, indent + "  ", v.lin_backward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINTCLOUD_TO_LASERSCAN_MESSAGE_VELOCITY_MULTIPLIER_H
