(cl:defpackage geobot_navigation-msg
  (:use )
  (:export
   "<GAPDIRECTION>"
   "GAPDIRECTION"
   "<SETGOALACTION>"
   "SETGOALACTION"
   "<SETGOALGOAL>"
   "SETGOALGOAL"
   "<SETGOALRESULT>"
   "SETGOALRESULT"
   "<SETGOALFEEDBACK>"
   "SETGOALFEEDBACK"
   "<SETGOALACTIONFEEDBACK>"
   "SETGOALACTIONFEEDBACK"
   "<SETGOALACTIONGOAL>"
   "SETGOALACTIONGOAL"
   "<SETGOALACTIONRESULT>"
   "SETGOALACTIONRESULT"
  ))

