; Auto-generated. Do not edit!


(cl:in-package geobot_navigation-msg)


;//! \htmlinclude SetGoalFeedback.msg.html

(cl:defclass <SetGoalFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SetGoalFeedback (<SetGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name geobot_navigation-msg:<SetGoalFeedback> is deprecated: use geobot_navigation-msg:SetGoalFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetGoalFeedback>) ostream)
  "Serializes a message object of type '<SetGoalFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetGoalFeedback>) istream)
  "Deserializes a message object of type '<SetGoalFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetGoalFeedback>)))
  "Returns string type for a message object of type '<SetGoalFeedback>"
  "geobot_navigation/SetGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetGoalFeedback)))
  "Returns string type for a message object of type 'SetGoalFeedback"
  "geobot_navigation/SetGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetGoalFeedback>)))
  "Returns md5sum for a message object of type '<SetGoalFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetGoalFeedback)))
  "Returns md5sum for a message object of type 'SetGoalFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetGoalFeedback>)))
  "Returns full string definition for message of type '<SetGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetGoalFeedback)))
  "Returns full string definition for message of type 'SetGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetGoalFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetGoalFeedback
))
