; Auto-generated. Do not edit!


(cl:in-package geobot_navigation-msg)


;//! \htmlinclude SetGoalResult.msg.html

(cl:defclass <SetGoalResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SetGoalResult (<SetGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name geobot_navigation-msg:<SetGoalResult> is deprecated: use geobot_navigation-msg:SetGoalResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetGoalResult>) ostream)
  "Serializes a message object of type '<SetGoalResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetGoalResult>) istream)
  "Deserializes a message object of type '<SetGoalResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetGoalResult>)))
  "Returns string type for a message object of type '<SetGoalResult>"
  "geobot_navigation/SetGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetGoalResult)))
  "Returns string type for a message object of type 'SetGoalResult"
  "geobot_navigation/SetGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetGoalResult>)))
  "Returns md5sum for a message object of type '<SetGoalResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetGoalResult)))
  "Returns md5sum for a message object of type 'SetGoalResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetGoalResult>)))
  "Returns full string definition for message of type '<SetGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetGoalResult)))
  "Returns full string definition for message of type 'SetGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetGoalResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SetGoalResult
))
