(cl:in-package ros2udp-msg)
(cl:export '(ROSTIME_-VAL
          ROSTIME_
          TRACESIZE_-VAL
          TRACESIZE_
          HEADERSIZE_-VAL
          HEADERSIZE_
          HEADERID_-VAL
          HEADERID_
          STAMPCOUNT_-VAL
          STAMPCOUNT_
          TRACENUMBER_-VAL
          TRACENUMBER_
          ODOTICK_-VAL
          ODOTICK_
          TRACEPOS_-VAL
          TRACEPOS_
          DURATION_-VAL
          DURATION_
          TRACESTATUSFLAG_-VAL
          TRACESTATUSFLAG_
          NUMSTACKS_-VAL
          NUMSTACKS_
          HARDWAREFLAG_-VAL
          HARDWAREFLAG_
          TRACEDATA_-VAL
          TRACEDATA_
          DATASIZE_-VAL
          DATASIZE_
          SAMPLEINTERVAL_-VAL
          SAMPLEINTERVAL_
          FREQUENCY_-VAL
          FREQUENCY_
          STAMP-VAL
          STAMP
          COORDINATEFORMAT-VAL
          COORDINATEFORMAT
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          LATITUDE_LABEL-VAL
          LATITUDE_LABEL
          LONGITUDE_LABEL-VAL
          LONGITUDE_LABEL
          UTMZONE-VAL
          UTMZONE
))