(cl:in-package os5000s_compass-msg)
(cl:export '(HEADER-VAL
          HEADER
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          TEMPERATURE-VAL
          TEMPERATURE
          DEPTH-VAL
          DEPTH
          MAGNETIC_VECTOR_LENGTH-VAL
          MAGNETIC_VECTOR_LENGTH
          MX-VAL
          MX
          MY-VAL
          MY
          MZ-VAL
          MZ
          ACCELERATION_VECTOR_LENGTH-VAL
          ACCELERATION_VECTOR_LENGTH
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
))