(cl:in-package pointcloud_to_laserscan-msg)
(cl:export '(SHORTEST_DISTANCE_TO_OBSTACLE_LS-VAL
          SHORTEST_DISTANCE_TO_OBSTACLE_LS
          SHORTEST_DISTANCE_TO_OBSTACLE_RS-VAL
          SHORTEST_DISTANCE_TO_OBSTACLE_RS
          SHORTEST_DISTANCE_TO_OBSTACLE_FT-VAL
          SHORTEST_DISTANCE_TO_OBSTACLE_FT
          SHORTEST_DISTANCE_TO_OBSTACLE_BK-VAL
          SHORTEST_DISTANCE_TO_OBSTACLE_BK
          LEFT_SIDE_BLOCKED-VAL
          LEFT_SIDE_BLOCKED
          RIGHT_SIDE_BLOCKED-VAL
          RIGHT_SIDE_BLOCKED
          FRONT_SIDE_BLOCKED-VAL
          FRONT_SIDE_BLOCKED
))